#pragma once
#define G_DEFINE_CHAR_Y_POS_OFFSET 40.0f
#define G_DEFINE_SCORE_BASIC 100
#define G_DEFINE_DAMAGE_SHOTGUN_TO_PLAYER 10
#define G_DEFINE_DAMAGE_SHOTGUN_TO_ZOMBIE 100

#define G_MACRO_DEBUG_STR_INTERVAL 30