#pragma once
#define G_DEFINE_MAX_BASIC_ZOMBIE  5
#define G_DEFINE_CHAR_Y_POS_OFFSET 40.0f
#define G_DEFINE_SCORE_BASIC 100
#define G_DEFINE_DAMAGE_SHOTGUN_TO_PLAYER 10
#define G_DEFINE_DAMAGE_SHOTGUN_TO_ZOMBIE 100

#define G_MACRO_DEBUG_STR_INTERVAL 30


#define G_DEFINE_ANI_ZOMB_DIE L"ZOMBIE_DIE"
#define G_DEFINE_ANI_ZOMB_ATT L"ZOMBIE_ATTACK"
#define G_DEFINE_ANI_ZOMB_WLK L"ZOMBIE_WALK"
#define G_DEFINE_ANI_ZOMB_IDL L"ZOMBIE_IDLE"

#define G_DEFINE_UI_PLAYER1_HEALTH 2
#define G_DEFINE_UI_PLAYER2_HEALTH 4
#define G_DEFINE_UI_PLAYER1_BULLET 3
#define G_DEFINE_UI_PLAYER2_BULLET 5

enum G_OBJECT {
	G_OBJ_LAB = 0,
	G_OBJ_DROPSHIP,
	G_OBJ_CAR1,
	G_OBJ_CAR2,
	G_OBJ_CNT
};

enum G_HERO {
	G_HERO_TOM = 0,
	G_HERO_JAKE,
	G_HERO_CNT
};

enum G_ZOMB_ST {
	G_ZOMB_ST_WALK =0,
	G_ZOMB_ST_IDLE,
	G_ZOMB_ST_ATTACK,
	G_ZOMB_ST_DEAD,
	G_ZOMB_ST_CNT
};